name: Deploy CMS
on:
  push:
    paths:
      - 'client/projects/cms/**/*'
      - '.github/workflows/cms.workflow.yml'
jobs:
  deploy:
    if: contains(github.ref, 'master')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm --prefix client ci
      - name: Build
        run: npm run build:cms
        env:
          PUBLIC_CONFIG: ${{ secrets.PUBLIC_CONFIG }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:cms
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'intl-glyco-cb2de'
