name: Deploy Functions
on:
  push:
    paths:
      - 'functions/**/*'
      - '.github/workflows/functions.workflow.yml'
jobs:
  deploy:
    if: contains(github.ref, 'master')
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          npm ci
          npm --prefix functions ci
          npm --prefix functions run build
          sudo npm install -g firebase-tools
      - name: Set project
        run: npm run firebase -- use intl-glyco --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        run: npm run firebase -- deploy --only functions --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
