name: Deploy Website
on:
  push:
    paths:
      - 'client/projects/website/**/*'
      - '.github/workflows/website.workflow.yml'
jobs:
  deploy:
    if: contains(github.ref, 'master')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm --prefix client ci
      - name: Build
        run: npm --prefix client run build:website
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:website
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'intl-glyco-cb2de'
